import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('organism_data.csv')

plt.figure()
plt.plot(data["generation"], data["total_organisms"], label="Total Population")
plt.plot(data["generation"], data["avg_energy"], label="Average Energy")
plt.xlabel("Generation")
plt.ylabel("Total Organisms")
plt.title("Population Over Time")
plt.legend()
plt.savefig('population_over_time.png')
# plt.show()

plt.figure()
plt.plot(data["generation"], data["avg_speed"], label="Average Speed")
plt.plot(data["generation"], data["avg_size"], label="Average Size")
plt.plot(data["generation"], data["avg_reproduction_threshold"], label="Average Reproduction Threshold")
plt.plot(data["generation"], data["avg_energy"], label="Average Energy")
plt.xlabel("Generation")
plt.ylabel("Average Trait Value")
plt.title("Trait Evolution Over Time")
plt.legend()
plt.savefig('trait_evolution_over_time.png')
# plt.show()

predators_data = pd.read_csv('predator_data.csv')

plt.figure()
plt.plot(predators_data["generation"], predators_data["total_predators"], label="Total Predators")
plt.plot(predators_data["generation"], predators_data["avg_energy"], label="Average Energy")
plt.xlabel("Generation")
plt.ylabel("Total Predators")
plt.title("Predator Population Over Time")
plt.legend()
plt.savefig('predator_population_over_time.png')

plt.figure()
plt.plot(predators_data["generation"], predators_data["avg_speed"], label="Average Speed")
plt.plot(predators_data["generation"], predators_data["avg_size"], label="Average Size")
plt.plot(predators_data["generation"], predators_data["avg_reproduction_threshold"], label="Average Reproduction Threshold")
plt.plot(predators_data["generation"], predators_data["avg_energy"], label="Average Energy")
plt.xlabel("Generation")
plt.ylabel("Average Trait Value")
plt.title("Predator Trait Evolution Over Time")
plt.legend()
plt.savefig('predator_trait_evolution_over_time.png')